apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: visa-vibe-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/visa-vibe-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "80"
        - name: VITE_CLERK_PUBLISHABLE_KEY
          value: "pk_test_cGxlYXNhbnQtcG9ycG9pc2UtOTcuY2xlcmsuYWNjb3VudHMuZGV2JA"
        - name: VITE_API_BASE_URL
          value: "https://server.visa-kal.co.il/"
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true

