apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: visa-vibe-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: visa-kal-frontend@strong-planet-483808-d1.iam.gserviceaccount.com
      containers:
      - image: gcr.io/strong-planet-483808-d1/visa-vibe-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: VITE_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: VITE_FIREBASE_API_KEY
              key: latest
        - name: VITE_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: VITE_FIREBASE_APP_ID
              key: latest
        - name: VITE_FIREBASE_AUTH_DOMAIN
          value: "strong-planet-483808-d1.firebaseapp.com"
        - name: VITE_FIREBASE_PROJECT_ID
          value: "strong-planet-483808-d1"
        - name: VITE_FIREBASE_STORAGE_BUCKET
          value: "strong-planet-483808-d1.firebasestorage.app"
        - name: VITE_FIREBASE_MESSAGING_SENDER_ID
          value: "249130274218"
        - name: VITE_FIREBASE_MEASUREMENT_ID
          value: "G-8DS1KLSVTV"
        - name: VITE_USE_FIREBASE_EMULATOR
          value: "false"
        - name: VITE_API_BASE_URL
          value: "https://server.visa-kal.co.il/"
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true

